#!/bin/sh
set -eu

# Generate allowlist file for locking down origin to Cloudflare only.
# Cloudflare publishes authoritative ranges here:
# - https://www.cloudflare.com/ips-v4
# - https://www.cloudflare.com/ips-v6
#
# Output: /etc/nginx/conf.d/cloudflare-allow.conf
# Usage in nginx.conf:
#   include /etc/nginx/conf.d/cloudflare-allow.conf;
#
# Note: if fetch fails, we keep the last generated file (if any) to avoid accidental lockout.

OUT="/etc/nginx/conf.d/cloudflare-allow.conf"
TMP="${OUT}.tmp"

echo "# Autogenerated at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > "$TMP"
echo "# Cloudflare IP ranges allowlist" >> "$TMP"

ok="1"
v4="$(curl -fsSL https://www.cloudflare.com/ips-v4 || true)"
v6="$(curl -fsSL https://www.cloudflare.com/ips-v6 || true)"

if [ -z "${v4}" ] && [ -z "${v6}" ]; then
  ok="0"
fi

if [ "$ok" = "1" ]; then
  echo "$v4" | while IFS= read -r cidr; do
    [ -n "$cidr" ] && echo "allow ${cidr};" >> "$TMP"
  done
  echo "$v6" | while IFS= read -r cidr; do
    [ -n "$cidr" ] && echo "allow ${cidr};" >> "$TMP"
  done
  echo "deny all;" >> "$TMP"
  mv "$TMP" "$OUT"
  echo "Generated Cloudflare allowlist: $OUT"
else
  rm -f "$TMP"
  echo "WARN: Could not fetch Cloudflare IP ranges; keeping existing $OUT if present." >&2
fi

